SELECT C.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TMP_TOTAL_SALES) AS TOTAL_SALES
FROM (
    SELECT AUTHOR_ID, A.BOOK_ID, CATEGORY, SUM(SALES) * PRICE AS TMP_TOTAL_SALES FROM BOOK AS A 
JOIN BOOK_SALES AS B ON A.BOOK_ID = B.BOOK_ID
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1 
GROUP BY B.BOOK_ID
) AS C
JOIN AUTHOR AS D ON C.AUTHOR_ID = D.AUTHOR_ID
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC