SELECT CAR_ID, CAR_TYPE, FLOOR(DAILY_FEE * 30 * (100 - (
    SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = A.CAR_TYPE AND DURATION_TYPE = '30일 이상'
)) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A
WHERE CAR_TYPE IN ('세단', 'SUV') AND CAR_ID NOT IN (
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE END_DATE >= '2022-11-01'
)  AND (FLOOR(DAILY_FEE * 30 * (100 - (
    SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = A.CAR_TYPE AND DURATION_TYPE = '30일 이상'
)) / 100) BETWEEN 500000 AND 2000000)
ORDER BY FEE DESC, CAR_TYPE ASC