SET @TARGET_USER_COUNT = (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021);

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT(USER_ID)) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT(USER_ID)) / @TARGET_USER_COUNT, 1) AS PURCHASED_RATIO
FROM ONLINE_SALE 
WHERE USER_ID IN (
    SELECT USER_ID FROM USER_INFO WHERE YEAR(JOINED) = 2021
)
GROUP BY MONTH(SALES_DATE) + YEAR(SALES_DATE) * 100
ORDER BY YEAR ASC, MONTH ASC