-- 코드를 입력하세요
SELECT FLAVOR FROM (
SELECT A.SHIPMENT_ID, A.FLAVOR, A.TOTAL_ORDER+B.TOTAL_ORDER AS TOTAL FROM FIRST_HALF AS A
JOIN (
    SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER FROM JULY GROUP BY FLAVOR
) AS B
ON A.SHIPMENT_ID = B.SHIPMENT_ID

ORDER BY TOTAL DESC 
LIMIT 3
) AS C